spring:
  datasource:
    url: jdbc:postgresql://itrd-pgsql-sit.h3c.com:5432/iam-test
    username: h3ciam
    password: Hello123
    driver-class-name: org.postgresql.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

#
#spring:
#  datasource:
#    druid:
#      url: jdbc:postgresql://itrd-pgsql-sit.h3c.com:5432/iam-test
#      username: h3ciam
#      password: Hello123
#      driver-class-name: org.postgresql.Driver