server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://itrd-mysql-sit.h3c.com:3306/studentmanager?serverTimezone=UTC
      username: root
      password: Hello@123

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: s_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



