jwt:
  # \u5BC6\u94A5
  secret: abc123
  #token\u8FC7\u671F\u65F6\u95F4  \u5355\u4F4D\u5C0F\u65F6
  expireTime: 1
spring:
  datasource:
    url: jdbc:mysql://itrd-mysql-sit.h3c.com:3306/edusoft?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hello@123

