server:
  port: 80
spring:
  profiles:
    active: @profile.active@
    group:
      "dev": devMVC,devRedis,test
      "pro": proMVC
#    include: devMVC,devRedis
logging:
  #    设置分组
  group:
    ebank: com.h3c.controller,com.h3c.entity
    iservice: com.alibaba
  level:
    root: info
    #    设置某个包的日志级别
    #    com.h3c.controller: debug
    #    设置分组，对某个级设置日志级别
    ebank: debug


  file:
    name: server.log
  logback:
    rollingpolicy:
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
      max-file-size: 3KB


